# Discovery Server Access
eureka:
  instance:
    hostname: localhost
  client:
    registryFetchIntervalSeconds: 1
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/

# HTTP (Tomcat) server port
server:
  port: 9002

#cart:
 #ribbon:
  #listOfServers: localhost:9003
