# Discovery Server Access
eureka:
   instance:
      hostname: localhost
   client:
      registryFetchIntervalSeconds: 1
      serviceUrl:
         defaultZone: http://localhost:8001/eureka/
# HTTP (Tomcat) server port
server:
   port: 9001
   
product:
 ribbon:
  listOfServers: localhost:9004