eureka:
 instance:
  hostname: localhost
  port: 8001

 client:
  serviceUrl:
   defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  registerWithEureka: false
  fetchRegistry: false
  server:
   waitTimeInMsWhenSyncEmpty: 0
