spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/venkataravuri/config-repo

eureka:
 instance:
  hostname: localhost
  port: 8002
 client:
  registryFetchIntervalSeconds: 1
  serviceUrl:
   defaultZone: http://localhost:8001/eureka/